server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopclothes_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

jwt:
  privateKey: BuyWkVX1rtFgUgIMNDTAmXMfs7t4TbvhZxOJWfULYSQ=

api:
  prefix: api/v1